version: '3'
services:
  backend:
    image: node:16
    container_name: express-backend
    working_dir: /
    volumes:
      - ./:/
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: bash -c "npm install && node index.js"
    restart: unless-stopped