version: '3'
services:
  backend:
    build: .
    container_name: express-backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    command: npm start
    restart: unless-stopped