version: '3'
services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3002"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm start
    restart: unless-stopped