version: '3'
services:
  backend:
    image: node:16
    container_name: express-backend
    working_dir: /app
    volumes:
      - .:/app  # Asegúrate de que el '.' se refiere al directorio raíz donde está package.json
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    command: bash -c "npm install && npm start"
    restart: unless-stopped